### ISSUE TITLE
Only works with exactly 5 pictures

### ISSUE THREAD

**Issue by mawilmsen** [benkimo6i/vanilla-js-carousel#1]
First of all, I love your clean & lightweight implementation. Should get more attention.

I would like to use it in a project but need to have an implementation which works for 1-n pictures, which doesn't work using your example JS (it requires exactly 5 pictures). Do you have any ambitions to change the sample code to works with any number of images?

 / Marc

**Comment by benkimo6i** [comment]
Hello! Thank you for submitting an issue and for your patience 🙏 I know it's been over a year but I've updated the code with a button to add more slides to the gallery and it should also support any number of images. I had to disable the gallery nav due to a refactor in the code but I have a redesign in the works that I am planning to add it back in once it's ready
