### ISSUE TITLE
How can we add multiple caraousel with different images?

### ISSUE THREAD

**Issue by killshotxd** [benkimo6i/vanilla-js-carousel#7]
Not able to seperately add carousels with different images

**Comment by benkimo6i** [comment]
Oh thanks, good callout!

I'll have to get a patch started on this and test, but this would be one way I would approach adding different images:

So if we take a look at lines 3-28 in the JS file: 

```
class Carousel {
  constructor(el) {
    this.el = el;
    this.carouselOptions = ['previous', 'add', 'play', 'next'];
    this.carouselData = [
      {
        'id': '1',
        'src': 'http://fakeimg.pl/300/?text=1',
      },
      {
        'id': '2',
        'src': 'http://fakeimg.pl/300/?text=2',
      },
      {
        'id': '3',
        'src': 'http://fakeimg.pl/300/?text=3',
      },
      {
        'id': '4',
        'src': 'http://fakeimg.pl/300/?text=4',
      },
      {
        'id': '5',
        'src': 'http://fakeimg.pl/300/?text=5',
      }
    ];
   ```
    
Instead of hardcoding the array inside the constructor, we need to pass data into the constructor `constructor(el, data) {` and then `this.carouselData = data`

and then create a variable and name it `myData`, this would be the variable we're passing through into the constructor which is then used as `this.carouselData`:

```
let myData = [
      {
        'id': '1',
        'src': 'http://fakeimg.pl/300/?text=1',
      },
      {
        'id': '2',
        'src': 'http://fakeimg.pl/300/?text=2',
      },
      {
        'id': '3',
        'src': 'http://fakeimg.pl/300/?text=3',
      },
      {
        'id': '4',
        'src': 'http://fakeimg.pl/300/?text=4',
      },
      {
        'id': '5',
        'src': 'http://fakeimg.pl/300/?text=5',
      }
    ];
```
    
and then we create a new carousel object: `const exampleCarousel = new Carousel(el, myData);`

and switch out the `src` values with whatever valid image url you want to use and that should work.

**Comment by killshotxd** [comment]
Okay Thanks will surely check it out.
